### ISSUE TITLE
morphyObjects are single use

### ISSUE THREAD

**Issue by ms609** [mbrazeau/MorphyLib#15]
Sending the same morphy object the same data twice generates different results: the correct result on the first call, a smaller number on the second.

Here's one dataset in which I've noticed the effect:
```
tree: (((((1,2),3),4),5),6);
character data (one taxon per line):
2 2 2
2 2 2
1 2 2
1 1 2
1 1 1
1 1 1
```

pseudocode:
```c
morphyObj = initialize_morphy_obj(tree_attributes, character_attributes);
score1 = calculate_length(tree->parent_array, tree->children_array, morphyObj); // returns correct value
score2 = calculate_length(tree->parent_array, tree->children_array, morphyObj); // returns lower value
candidate_tree = NNI_rearrange(tree);
score3 = calculate_length(candidate->parent_array, candidate->children_array, morphyObj); // returns nonsense
```

My feeling is that tree search will be more efficient if a morphyObj can be initialized once, and interrogated with different topologies; creating a new morphyObj each time involves unnecessary parsing of character data and weights, etc.

It seems to me that this should not be too difficult to implement, as the C code already treats each pass separately?

**Comment by mbrazeau** [comment]
I'm not sure what is happening or that it's not related to your code. None of these function calls are MorphyLib functions. Of course you don't need to reallocate or reinitialise a morphy object every time you calculate a length, and so far I have not had this problem

As it stands, you certainly only need to allocate a morphy object once per analysis, rather than re-sending it the data every time. That will only cause errors.

.

**Comment by ms609** [comment]
The actual code that I'm calling from R, with the same parameters each time, is MORPHYLENGTH in
https://github.com/ms609/inapplicable/blob/MorphyLib/src/RMorphy.c

The first call gives the correct score; each subsequent score gives the same incorrect score.

My initial thought is that a function such as mpl_finalize_tip might be adjusting the original tip data (rather than the final-uppass-tip-data)?

Here's some R code that will reproduce the problem
```r
  library('inapplicable') # Installed from MorphyLib branch
  # Load some example data
  true_tree <- read.tree(text = "(((((1,2),3),4),5),6);")
  tree <- RenumberTips(read.tree(text = "(((1, 6), 3), (2, (4, 5)));"), true_tree$tip.label)
  dataset <- StringToPhyDat('110000 111000 111100', 1:6, byTaxon=FALSE)

  morphyObj <- LoadMorphy(dataset)
  MorphyLength(tree, morphyObj) # Gives correct score 
  # MorphyLength doesn't touch the morphyObj object, it just .Calls MORPHYLENGTH
  MorphyLength(tree, morphyObj) # Now the score is wrong
  MorphyLength(tree, morphyObj) # Same again
  MorphyLength(tree, morphyObj) # Same again
  morphyObj <- UnloadMorphy(morphyObj)
 
```

**Comment by mbrazeau** [comment]
It could be, especially given that `mpl_finalise_tip` isn't implemented yet (and is really only necessary if you're going to do indirect optimisation length counts), that could be causing problems with your tip data. At any rate, you shouldn't call `mpl_finalise_tip`.

**Comment by mbrazeau** [comment]
scratch that, it is implemented. Let me have a look.

**Comment by mbrazeau** [comment]
Again, none of these are Morphy functions. Can you point me to MorphyLength() ?

**Comment by mbrazeau** [comment]
I can't reproduce the result. I'm running a C++ driver for Morphy that can take in nexus files with trees and data. I reproduced your matrix and tree, calculated the length twice and got the same result.

When you get a 'wrong score', how wrong is it? Is it the same (wrong) value every time, or is the result different each time you run it?

I have a feeling that we might need to leave the MorphyObj pointer on the PROTECTED stack until mpl_delete_Morphy() is called.

**Comment by mbrazeau** [comment]
I just ran 40K test trees and could not reproduce the issue.

**Comment by mbrazeau** [comment]
I just pushed an updated version of RMorphyex.c to Rdev branch. It is not tested, but you might want to give it a try.

**Comment by ms609** [comment]
Thanks for taking a look.  Interesting that it's not reproducible at your end.  I'll have a shot with the new RMorphyex.c tomorrow.  I'll also take a look as to whether I can replicate the result by duplicating the code within the MORPHYLENGTH function, and try to narrow down where the steps are 'going missing'.

The "wrong" result is always the same value (4, should be 8), after several re-starts of R, so it has the feel of something being changed systematically.  Hopefully that means I'll be able to pin down the issue quickly enough.

**Comment by mbrazeau** [comment]
Yes, but I don't think it's a problem in the core library. And when I run your exact script locally, I get all 6s for the length.

**Comment by ms609** [comment]
Had a shot with the updated RMorphyex.c but it threw warnings; I've uploaded an alternative approach to the Rdev branch (though I note that the garbage collection function I put in can cause R to crash when it quits, so I've done something wrong there...)

I've spent a bit of time tracking down a reproducible example: when you get the chance, would you mind running the below code and seeing whether you get the same results as I do?

```r
library(inapplicable)
dataset <- StringToPhyDat('110000 111000 111100', 1:6, byTaxon=FALSE)
morphyObj <- LoadMorphy(dataset)
   ANCESTORS = c(9, 6, 8, 10, 10, 8, 6, 9, 7, 6, 7)
   LEFT      = c(9, 10, 5, 0, 4)
   RIGHT     = c(1, 8, 2, 7, 3)
.Call('MORPHYLENGTH', as.integer(ANCESTORS), as.integer(LEFT), 
               as.integer(RIGHT), morphyObj, PACKAGE='inapplicable') # = 6
.Call('MORPHYLENGTH', as.integer(ANCESTORS), as.integer(LEFT), 
               as.integer(RIGHT), morphyObj, PACKAGE='inapplicable') # = 5
.Call('MORPHYLENGTH', as.integer(ANCESTORS), as.integer(LEFT), 
               as.integer(RIGHT), morphyObj, PACKAGE='inapplicable') # = 5, ad infinitum
```


The next thing I want to explore is whether using a separate dummy root, rather than setting the root as its own ancestor, makes a difference here.

**Comment by mbrazeau** [comment]
This I can reproduce, again, using these R calls. So far, no evidence that this is in the library.

I notice you call mpl_update_lower_root() on the root itself. That's not yet supported. While I know that will work one time around, I am not sure how that will go in subsequent rounds. You might want to use a dummy root, as expected, and thus call the function on a separate nodal set. Try that, see what happens.

**Comment by ms609** [comment]
I've modified the code to use a separate dummy root node, and change the Ancestors array accordingly:
```r
   ANCESTORS = c(9, 6, 8, 10, 10, 8, 11, 9, 7, 6, 7) # With dummy root as root's parent
```
But I'm still receiving the same results.

**Comment by ms609** [comment]
Gotcha.  The issue was that the node are not listed in Postorder sequence: Node 7 is a child of node 9.

```
Downpass on node 10 -< 4,3 ... pscore is 1
Downpass on node 9 -< 0,7 ... pscore is 4
Downpass on node 8 -< 5,2 ... pscore is 6
Downpass on node 7 -< 10,8 ... pscore is 6
Downpass on node 6 -< 9,1 ... pscore is 6
Uppass on node 6 -< 9,1 ... pscore is 6
Uppass on node 7 -< 10,8 ... pscore is 6
Uppass on node 8 -< 5,2 ... pscore is 6
Uppass on node 9 -< 0,7 ... pscore is 6
Uppass on node 10 -< 4,3 ... pscore is 6

 - Final pscore was 6. Repeating: 

Downpass on node 10 -< 4,3 ... pscore is 1
Downpass on node 9 -< 0,7 ... pscore is 3
Downpass on node 8 -< 5,2 ... pscore is 5
Downpass on node 7 -< 10,8 ... pscore is 5
Downpass on node 6 -< 9,1 ... pscore is 5
Uppass on node 6 -< 9,1 ... pscore is 5
Uppass on node 7 -< 10,8 ... pscore is 5
Uppass on node 8 -< 5,2 ... pscore is 5
Uppass on node 9 -< 0,7 ... pscore is 5
Uppass on node 10 -< 4,3 ... pscore is 5
 - This time, Final pscore was 5 
```
