### ISSUE TITLE
Building library for R

### ISSUE THREAD

**Issue by ms609** [mbrazeau/MorphyLib#3]
I've tried following the instructions in README, but to no avail.

Navigating first to `[path_to...]\MorphyLib\` and running `>make` in the console seems to work as expected, producing the .a file and a companion .so . (Should this be a .dll on windows?)

Then navigating to `[path_to...]\MorphyLib\R\src` and executing 

`>R CMD SHLIB -o RMorphyEx.so RMorphyex.c RMorphyUtils.c ../../libmorphy_i686-MINGW32_NT-6.2.a`
is unhappy, returning 
```
c:/Rtools/mingw_64/bin/gcc -shared -s -static-libgcc -o RMorphyEx.so tmp.def RMorphyex.o RMorphyUtils.o ../../libmorphy_i686-MINGW32_NT-6.2.a -Ld:/Compiler/gcc-4.9.3/local330/lib/x64 -Ld:/Compiler/gcc-4.9.3/local330/lib -LC:/PROGRA~1/R/R-3.3.3/bin/x64 -lR
RMorphyex.o:RMorphyex.c:(.text+0x5): undefined reference to `mpl_new_Morphy'
RMorphyex.o:RMorphyex.c:(.text+0x5f): undefined reference to `mpl_delete_Morphy'
RMorphyex.o:RMorphyex.c:(.text+0xe0): undefined reference to `mpl_init_Morphy'
RMorphyex.o:RMorphyex.c:(.text+0x14b): undefined reference to `mpl_get_numtaxa'
RMorphyex.o:RMorphyex.c:(.text+0x1ab): undefined reference to `mpl_get_num_charac'
RMorphyex.o:RMorphyex.c:(.text+0x223): undefined reference to `mpl_attach_symbols'
RMorphyex.o:RMorphyex.c:(.text+0x27b): undefined reference to `mpl_get_symbols'
RMorphyex.o:RMorphyex.c:(.text+0x2e9): undefined reference to `mpl_attach_rawdata'
RMorphyex.o:RMorphyex.c:(.text+0x33f): undefined reference to `mpl_delete_rawdata'
RMorphyex.o:RMorphyex.c:(.text+0x3d0): undefined reference to `mpl_set_parsim_t'
RMorphyex.o:RMorphyex.c:(.text+0x44c): undefined reference to `mpl_set_num_internal_nodes'
RMorphyex.o:RMorphyex.c:(.text+0x4ab): undefined reference to `mpl_get_num_internal_nodes'
RMorphyex.o:RMorphyex.c:(.text+0x50b): undefined reference to `mpl_apply_tipdata'
RMorphyex.o:RMorphyex.c:(.text+0x59f): undefined reference to `mpl_first_down_recon'
RMorphyex.o:RMorphyex.c:(.text+0x646): undefined reference to `mpl_first_up_recon'
RMorphyex.o:RMorphyex.c:(.text+0x6df): undefined reference to `mpl_second_down_recon'
RMorphyex.o:RMorphyex.c:(.text+0x786): undefined reference to `mpl_second_up_recon'
RMorphyex.o:RMorphyex.c:(.text+0x80d): undefined reference to `mpl_update_tip'
RMorphyex.o:RMorphyex.c:(.text+0x88d): undefined reference to `mpl_update_lower_root'
collect2.exe: error: ld returned 1 exit status
```

It looks like the compiler is unable to find the functions in mpl.c.  Could this be because it is creating a .so instead of a .dll, or is it that the compiler is unable to find the compiled mpl.o file?

**Comment by mbrazeau** [comment]
"Undefined reference" means that it can't find the function definition, which are all stored in the static lib (the '.a' file). As this output is a complete list of the API functions (none of which have been re-named recently), the problem appears to be that the linker isn't finding the .a file. I would check that the path ('../../') is in fact correct. Your make system may have put the target in a different directory.

**Comment by mbrazeau** [comment]
And it is quite likely that .so should be .dll on windows.

**Comment by ms609** [comment]
The path is correct - I've tried changing it and it gives a "file not found error".  
I've tried modifying the `R CMD SHLIB` command, replacing `-o RMorphyEx.so` with `-o RMorphyEx.dll`, and see the same error.
I also tried modifying the makefile, replacing `DNAME	:= $(NAME).so` with `DNAME	:= $(NAME).dll` , which didn't help – I wonder if there are other modifications to the makefile required to generate a library that Windows can understand?

**Comment by mbrazeau** [comment]
You shouldn't need to tamper with the Makefile at this stage, since you're not linking against the dylib from that build. You could just replace the static library with a path to a wildcard for all the .c source files:

`R CMD SHLIB Morphex.c RMorphyUtils.c ./path/to/src/*.c`

**Comment by ms609** [comment]
Tried that... and got the same error, along with a hundred more undefined references to functions such as `_free`, `calloc`, `__assert` and other C internals

**Comment by mbrazeau** [comment]
Could you email me the output?

**Comment by ms609** [comment]
On its way

**Comment by ms609** [comment]
Ooh - I tried again with ../../src/*.c and god a more promising result.  I'll take a look and update in a tick

**Comment by mbrazeau** [comment]
Ah, good. Looking at your output, it looks like implementation differences for a bunch of the standard C library functions between MinGW and whatever R is using. So, the builds aren't cross-compatible.

**Comment by ms609** [comment]
I see.  Though is not R CMD SHLIB using MINGW?

**Comment by mbrazeau** [comment]
Yeah, but it is likely that our Makefile and the R CMD SHLIB are using different C implementations. I notice that R invokes the `-std=gnu99` flag, whereas our Makefile doesn't do that explicitly.

**Comment by ms609** [comment]
Huh, I just ran it again and I have a .dll!  
Not sure what changed... I tried running 'cmake' instead of 'make' in the root directory but that generated an error and didn't seem to produce any output.

Now to see whether the .dll works!

**Comment by mbrazeau** [comment]
yes, if you leave out the `-o libname.so` it should automatically generate a .dll on Windows.

**Comment by ms609** [comment]
No error messages that time though.  And I have run mpl_init_Morphy in R without crashing anything.  Looks extremely promising!

**Comment by mbrazeau** [comment]
Great! Check the return from that function. It should say it's a pointer value.

**Comment by ms609** [comment]
It is.  I've correctly set and get the number of taxa and characters, now I'm wrestling with attaching symbols.

**Comment by mbrazeau** [comment]
You can skip the 'attach symbols' bit; MorphyLib will extract all of them from a matrix for you. But if it's throwing errors (i.e. negative numbers), let me know what you're getting.

**Comment by ms609** [comment]
The error message I'm receiving is
`Warning: stack imbalance in '.Call', 14 then 13`

R politely gives me a blank line, but the next thing I do causes a crash.

**Comment by mbrazeau** [comment]
OK, that's a problem in the C wrappers in RMorphyex.c. I'll investigate. This typically means we omitted an "UNPROTECT".

**Comment by mbrazeau** [comment]
Yup. There was an extraneous UNPROTECT call in the wrapper. I've removed it and pushed an update.
