### ISSUE TITLE
mpl_attach_rawdata error

### ISSUE THREAD

**Issue by ms609** [mbrazeau/MorphyLib#4]
I'm working with a dataset with 67 taxa and 125 characters. (Nothing like starting small then building up, is there!)

I'm calling mpl_attach_rawdata(as.character(matrix_as_string), morphy) and receive the error code -6, listed in mplerror.h as "ERR_DIMENS_OVER".  

But nchar(matrix_as_string) = 67*125.

**Comment by mbrazeau** [comment]
Can you post the data string you're inputting? Is there a terminal semicolon? What punctuation is used for polymorphisms?

Error code 6 or -6? There shouldn't be positive error codes coming from MorphyLib.

**Comment by ms609** [comment]
There was no terminal semicolon.  Adding this makes it work.  I've updated the doc accordingly.
