### ISSUE TITLE
Root node

### ISSUE THREAD

**Issue by ms609** [mbrazeau/MorphyLib#7]
It's not clear what should be specified as anc_id at the root node in mpl_frst_up_recon.  Currently this function crashes whatever I do...

**Comment by ms609** [comment]
Just discovered mpl_update_lower_root.

**Comment by mbrazeau** [comment]
For now, yes, it should be its own node, but in theory, you could point `mpl_update_lower_root` to the upper root (i.e. set both indices as the same) and it would work. However, I've not yet tested that (give it a try and see what happens). Ultimately, it would depend on how a calling program structures its trees and deals with the need for uppass functions to call from an ancestral node. The goal in the 'final' implementation will be to ensure it works on rooted and unrooted trees equally well. For now, it will probably crash.

**Comment by ms609** [comment]
Hmm, your suggestion seems to work.  I'll keep the dummy node in my code for now though... just to be safe! (-:
