### ISSUE TITLE
Score calculated as... zero

### ISSUE THREAD

**Issue by ms609** [mbrazeau/MorphyLib#9]
I've pushed a simple test case in SimpleTest.R.  
On each pass, the score returned by `mpl_second_down_recon` and equivalent functions is 0; it should be non-zero.

With a larger and more complicated (125 chars, 67 taxa) dataset, I am seeing a score calculated on the first downpass (typically in the order of 3-12, and not the same every time!) and scores of zero on all other passes.

Any thoughts?

**Comment by TGuillerme** [comment]
Not sure. The way Martin dealt with errors is by outputting `0` for a success (so it seems not that bad that it only spits out 0s). There might be a problem with the R wrapper that doesn't handle the output of the passes correctly (i.e. doesn't return the right integer). I'm currently going through it (although my machine is really slow and prone to crashes today - running a lot of PAUP searches - so it takes ages). I'll get back to you if I get it working on my side.

**Comment by ms609** [comment]
I see - so the "Score" is the score ADDED at that node, rather than the total score in the entire tree?.

(And I'd not realised that the characters were columns, rather than rows, which makes sense now that you point it out.)

**Comment by mbrazeau** [comment]
It's the score *at* that particular node (uncorrected for ambiguous optimisation, of course). Of course the only reason to return the score in each iteration would be if it is the added score. Otherwise, just get it at the end.

**Comment by ms609** [comment]
I couldn't find a function that would do that – could you point me in the right direction?

**Comment by mbrazeau** [comment]
It doesn't exist yet. Add the length, rather than overwriting your own variable. This issue is closed.
